backtest:
  initial_balance: 10000.0
  commission: 0.001
  window_size: 50
indicators:
  rsi:
    period: 14
    oversold: 30
    overbought: 70
risk_management:
  max_position_size: 3000.0
  stop_loss_atr: 3.0
